site_name: Kube-OVN 文档
repo_url: https://github.com/kubeovn/docs/
nav:
  - 主页: 'index.md'
  - 快速入门:
      - 准备工作: 'start/prepare.md'
      - 一键安装: 'start/one-step-install.md'
      - Underlay 网络安装: 'start/underlay.md'
      - 卸载: 'start/uninstall.md'
  - 使用指南:
      - 固定地址: 'guide/static-ip-mac.md'
      - 容器网络 QoS 配置: 'guide/qos.md'
      - 配置监控和面板: 'guide/prometheus-grafana.md'
  - 高级功能:
      - 多网卡管理: 'advance/multi-nic.md'
  - 开发指南:
      - 开发环境构建: 'develop/dev-env.md'
  - 技术参考:
      - Underlay 流量拓扑: 'reference/underlay-topology.md'
theme:
    name: readthedocs
markdown_extensions:
  - footnotes
