name: markdown-lint
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  markdown-lint:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: lint
        run: |
          npm install -g markdownlint-cli
          markdownlint **/*.md --disable MD013 MD033 MD045 MD024 MD041